"""initial schema

Revision ID: 8d0f765b34e3
Revises: 
Create Date: 2026-06-23 16:00:55.309119
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # available for JSONB(astext_type=Text()) renderings
from sqlalchemy.dialects import postgresql
import mostaql_notifier.db.types

revision: str = '8d0f765b34e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_state',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_app_state'))
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mostaql_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('profile_url', sa.String(), nullable=True),
    sa.Column('hiring_rate', sa.Float(), nullable=True),
    sa.Column('projects_posted', sa.Integer(), nullable=True),
    sa.Column('projects_open', sa.Integer(), nullable=True),
    sa.Column('hires_count', sa.Integer(), nullable=True),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('reviews_count', sa.Integer(), nullable=True),
    sa.Column('total_spent', sa.Numeric(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('member_since', sa.String(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('last_refreshed_at', mostaql_notifier.db.types.UtcDateTime(), nullable=False),
    sa.Column('first_seen_at', mostaql_notifier.db.types.UtcDateTime(), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients')),
    sa.UniqueConstraint('mostaql_id', name=op.f('uq_clients_mostaql_id'))
    )
    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', mostaql_notifier.db.types.UtcDateTime(), nullable=False),
    sa.Column('finished_at', mostaql_notifier.db.types.UtcDateTime(), nullable=True),
    sa.Column('found_count', sa.Integer(), nullable=False),
    sa.Column('new_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('running', 'success', 'partial', 'failed', 'blocked', name='run_status', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scrape_runs'))
    )
    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('value_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings'))
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mostaql_id', sa.String(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('skills', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('budget_min', sa.Numeric(), nullable=True),
    sa.Column('budget_max', sa.Numeric(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('bids_count', sa.Integer(), nullable=True),
    sa.Column('posted_at', mostaql_notifier.db.types.UtcDateTime(), nullable=True),
    sa.Column('scraped_at', mostaql_notifier.db.types.UtcDateTime(), nullable=False),
    sa.Column('site_status', sa.Enum('open', 'closed', 'unknown', name='project_status', native_enum=False), nullable=False),
    sa.Column('eval_status', sa.Enum('baseline', 'pending', 'qualified', 'disqualified', 'eval_error', name='eval_status', native_enum=False), nullable=False),
    sa.Column('eval_attempts', sa.Integer(), nullable=False),
    sa.Column('last_eval_at', mostaql_notifier.db.types.UtcDateTime(), nullable=True),
    sa.Column('qualified_at', mostaql_notifier.db.types.UtcDateTime(), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_projects_client_id_clients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('mostaql_id', name=op.f('uq_projects_mostaql_id'))
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('ix_projects_eval_status', ['eval_status'], unique=False)
        batch_op.create_index('ix_projects_posted_at', ['posted_at'], unique=False)
        batch_op.create_index('ix_projects_qualified_at', ['qualified_at'], unique=False)
        batch_op.create_index('ix_projects_scraped_at', ['scraped_at'], unique=False)

    op.create_table('notifications_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', mostaql_notifier.db.types.UtcDateTime(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('dedup_key', sa.String(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_notifications_log_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications_log')),
    sa.UniqueConstraint('dedup_key', name=op.f('uq_notifications_log_dedup_key'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications_log')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('ix_projects_scraped_at')
        batch_op.drop_index('ix_projects_qualified_at')
        batch_op.drop_index('ix_projects_posted_at')
        batch_op.drop_index('ix_projects_eval_status')

    op.drop_table('projects')
    op.drop_table('settings')
    op.drop_table('scrape_runs')
    op.drop_table('clients')
    op.drop_table('app_state')
    # ### end Alembic commands ###
