"""personal layer

Revision ID: 8e6070483eaf
Revises: 8d0f765b34e3
Create Date: 2026-06-28 14:53:33.202937
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # available for JSONB(astext_type=Text()) renderings
from sqlalchemy.dialects import postgresql
import mostaql_notifier.db.types

revision: str = '8e6070483eaf'
down_revision: Union[str, None] = '8d0f765b34e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('stored_name', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', mostaql_notifier.db.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_attachments_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments')),
    sa.UniqueConstraint('stored_name', name=op.f('uq_attachments_stored_name'))
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index('ix_attachments_project_id', ['project_id'], unique=False)

    op.create_table('personal_records',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('applied_at', mostaql_notifier.db.types.UtcDateTime(), nullable=True),
    sa.Column('won_amount', sa.Numeric(), nullable=True),
    sa.Column('lost_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('board_position', sa.Float(), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('status_changed_at', mostaql_notifier.db.types.UtcDateTime(), nullable=True),
    sa.Column('reminder_at', mostaql_notifier.db.types.UtcDateTime(), nullable=True),
    sa.Column('created_at', mostaql_notifier.db.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', mostaql_notifier.db.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_personal_records_project_id_projects')),
    sa.PrimaryKeyConstraint('project_id', name=op.f('pk_personal_records'))
    )
    with op.batch_alter_table('personal_records', schema=None) as batch_op:
        batch_op.create_index('ix_personal_records_favorite', ['favorite'], unique=False)
        batch_op.create_index('ix_personal_records_hidden', ['hidden'], unique=False)
        batch_op.create_index('ix_personal_records_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_records', schema=None) as batch_op:
        batch_op.drop_index('ix_personal_records_status')
        batch_op.drop_index('ix_personal_records_hidden')
        batch_op.drop_index('ix_personal_records_favorite')

    op.drop_table('personal_records')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index('ix_attachments_project_id')

    op.drop_table('attachments')
    # ### end Alembic commands ###
